---
title: "P8105 Homework 6"
author: "Kyung Suk Lee"
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: yes
---

```{r setup, include=FALSE}
library(tidyverse)
library(modelr)
library(mgcv)
library(p8105.datasets)

knitr::opts_chunk$set(out.width = "100%")

theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis")

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d

knitr::opts_chunk$set(comment = NA, message = FALSE, warning = FALSE, echo = TRUE)
```

## Problem 1

```{r}
homicide_df = 
  read_csv("./data/homicide-data.csv", na = c("", "NA", "Unknown")) %>%
  janitor::clean_names() %>% 
  mutate(
    city_state = str_c(city, state, sep = ", "),
    victim_age = as.numeric(victim_age),
    resolution = case_when(
      disposition == "Closed without arrest" ~ 0,
      disposition == "Open/No arrest"        ~ 0,
      disposition == "Closed by arrest"      ~ 1
  )) %>% 
  filter(!(city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL")),
         victim_race %in% c("White", "Black")) %>% 
  select(city_state, resolution, victim_age, victim_race, victim_sex)
```

```{r}
baltimore_df = 
  homicide_df %>% 
  filter(city_state == "Baltimore, MD")

glm(resolution ~ victim_age + victim_race + victim_sex,
    data = baltimore_df, family = binomial()) %>% 
  broom::tidy() %>% 
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96*std.error),
    CI_upper = exp(estimate + 1.96*std.error)
  ) %>% 
  select(term, OR, starts_with("CI")) %>% 
  knitr::kable(digits = 3,
               format = "html",
               caption = "Table: Estimate and confidence interval of the adjusted odds ratio")
```

```{r}
models_results_df = 
  homicide_df %>% 
    nest(data = -city_state) %>% 
    mutate(
      models = map(.x = data, ~glm(resolution ~ victim_age + victim_race + victim_sex,
                                   data = .x,
                                   family = binomial())),
      results = map(models, broom::tidy)
    ) %>% 
    select(city_state, results) %>% 
    unnest(results) %>% 
    mutate(
      OR = exp(estimate),
      CI_lower = exp(estimate - 1.96*std.error),
      CI_upper = exp(estimate + 1.96*std.error)
    ) %>% 
    select(city_state, term, OR, starts_with("CI"))
```

```{r}
models_results_df %>% 
  filter(term == "victim_raceWhite") %>% 
  mutate(city_state = fct_reorder(city_state, OR)) %>% 
  ggplot(aes(x = city_state, y = OR, color = city_state))+
  geom_point()+
  geom_errorbar(aes(ymin = CI_lower, ymax = CI_upper))+
  theme(axis.text.y = element_text(size = 6), legend.position = "none") +
  labs(
    title = "Odds Ratio by Cities",
    x = "City",
    y = "Odds Ratio",
    caption = "Datasource: The Washington Post",
    color = "") +
  theme(plot.title = element_text(face="bold",
                                  hjust=0.5,
                                  lineheight=1.2)) +
  scale_y_continuous(breaks = seq(0, 30, by = 1)) +
  coord_flip()
```

* **Comment on the plot**: The above plot illustrates that for most cities the estimates for odds ratio are above 1.0. Such result indicates that more homicides are likely to be solved for white compared to non-whites. We can observe that this is more apparent in cities such as Boston, Omaha, Oakland, and Pittsburgh.































